### ISSUE TITLE
Receives "Bad payload received by generic incoming webhook." as response

### ISSUE THREAD

**Issue by tinomerl** [astronomer/cs-tutorial-msteams-callbacks#5]
After upgrading to Airflow 2.5.1 recently the `ms_teams_webhook_hook.py` won't function anymore as intended. The error was in the summary and in the activityTitle overhanded to the webhook [here](https://github.com/astronomer/cs-tutorial-msteams-callbacks/blob/main/include/hooks/ms_teams_webhook_hook.py#L117). It was related to the quotation marks used in `self.message`. Double Quotes are used there and they seem to create a malformed payload. 
Replacing them with single quotes won't work either and also creates a malformed payload.

My best Idea to fix it was to 

```python
self.message = message
```
[here ](https://github.com/astronomer/cs-tutorial-msteams-callbacks/blob/main/include/hooks/ms_teams_webhook_hook.py#L64) with 

```python
self.message = message.replace('"', '\\"')
```

The Problem with this workaround is that the Message won't be formatted ideally anymore.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/35485536/225634044-adf231ae-5e3b-4ce4-a8ee-9600f3181965.png">

I'm open to better Ideas or to create a PR if guided what the best way to create one would be.

**Comment by TJaniF** [comment]
Thank you for submitting the issue! Fixed it for now, but yes, I also could not get it formatted nicely so open to ideas on that part 😄
